Module 3
mberkii/movies-api-react pull request #3
Opened 2024-10-06 12:05 UTC by mberkii

2024-10-09 10:14 UTC, EpamFanAnton requested changes

2024-10-09 10:14 UTC, EpamFanAnton commented on src/App.js
> +	const [selectedMovie, setSelectedMovie] = useState();
looks like something happened with tabulation here

2024-10-09 10:14 UTC, EpamFanAnton commented on src/App.js
> +						<MovieTile key={movie.id} details={movie} selectMovie={setSelectedMovie}/>
can't see onClick handler mentioned in the task description "Additionally, the component should receive a callback property to capture click event."

2024-10-09 10:14 UTC, EpamFanAnton commented on src/App.js
> +	const sortMovies = () => {
this name is not descriptive. this function returns sorted movies, not sorting them.

2024-10-09 10:29 UTC, mberkii commented on src/App.js
> +	const [selectedMovie, setSelectedMovie] = useState();
In VS Code everything is good, probably github misinterpreted these lines
![image](https://github.com/user-attachments/assets/89d25d69-f7fb-48ec-a4b8-aaf7874f17f7)

2024-10-10 07:35 UTC, EpamFanAnton approved these changes

2024-10-10 07:36 UTC, merged